// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: calculator/calculator_proto_ex/calculator_proto_experimental.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CalcRequest struct {
	Firstnumber          int64    `protobuf:"varint,1,opt,name=firstnumber,proto3" json:"firstnumber,omitempty"`
	Secondnumber         int64    `protobuf:"varint,2,opt,name=secondnumber,proto3" json:"secondnumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcRequest) Reset()         { *m = CalcRequest{} }
func (m *CalcRequest) String() string { return proto.CompactTextString(m) }
func (*CalcRequest) ProtoMessage()    {}
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f029a176d5aca005, []int{0}
}
func (m *CalcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcRequest.Unmarshal(m, b)
}
func (m *CalcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcRequest.Marshal(b, m, deterministic)
}
func (m *CalcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcRequest.Merge(m, src)
}
func (m *CalcRequest) XXX_Size() int {
	return xxx_messageInfo_CalcRequest.Size(m)
}
func (m *CalcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcRequest proto.InternalMessageInfo

func (m *CalcRequest) GetFirstnumber() int64 {
	if m != nil {
		return m.Firstnumber
	}
	return 0
}

func (m *CalcRequest) GetSecondnumber() int64 {
	if m != nil {
		return m.Secondnumber
	}
	return 0
}

type CalcResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalcResponse) Reset()         { *m = CalcResponse{} }
func (m *CalcResponse) String() string { return proto.CompactTextString(m) }
func (*CalcResponse) ProtoMessage()    {}
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f029a176d5aca005, []int{1}
}
func (m *CalcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcResponse.Unmarshal(m, b)
}
func (m *CalcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcResponse.Marshal(b, m, deterministic)
}
func (m *CalcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcResponse.Merge(m, src)
}
func (m *CalcResponse) XXX_Size() int {
	return xxx_messageInfo_CalcResponse.Size(m)
}
func (m *CalcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcResponse proto.InternalMessageInfo

func (m *CalcResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalcRequest)(nil), "calc.CalcRequest")
	proto.RegisterType((*CalcResponse)(nil), "calc.CalcResponse")
}

func init() {
	proto.RegisterFile("calculator/calculator_proto_ex/calculator_proto_experimental.proto", fileDescriptor_f029a176d5aca005)
}

var fileDescriptor_f029a176d5aca005 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x3b, 0x6b, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xba, 0x78, 0xb8, 0x76, 0x29, 0xd5, 0x50, 0x4a, 0x27, 0xa3, 0xa1, 0x74, 0x52,
	0xa1, 0x5d, 0x3b, 0xb9, 0xff, 0xc0, 0xda, 0xb2, 0x18, 0x59, 0xb9, 0x01, 0x83, 0x5e, 0xd1, 0x23,
	0xe4, 0xe7, 0x07, 0x3f, 0x20, 0x0a, 0x64, 0xbb, 0xf7, 0xe3, 0xf0, 0x71, 0x0e, 0x74, 0x52, 0x28,
	0x99, 0x94, 0x88, 0xd6, 0x7f, 0x5f, 0xcf, 0xc1, 0x79, 0x1b, 0xed, 0x80, 0xe7, 0x7b, 0xcc, 0xa1,
	0x9f, 0x34, 0x9a, 0x28, 0x14, 0x5b, 0x10, 0x79, 0x9a, 0x43, 0x94, 0x43, 0xfd, 0x2f, 0x94, 0xec,
	0xf1, 0x98, 0x30, 0x44, 0xd2, 0x42, 0x7d, 0x98, 0x7c, 0x88, 0x26, 0xe9, 0x11, 0xfd, 0x7b, 0xd1,
	0x16, 0x5f, 0x65, 0x9f, 0x23, 0x42, 0xa1, 0x09, 0x28, 0xad, 0xd9, 0x6f, 0x91, 0xc7, 0x25, 0x72,
	0xc3, 0xe8, 0x27, 0x34, 0xab, 0x34, 0x38, 0x6b, 0x02, 0x92, 0x37, 0xa8, 0x3c, 0x86, 0xa4, 0xe2,
	0x26, 0xdc, 0xbe, 0x9f, 0x3f, 0x00, 0x9e, 0x34, 0x47, 0x7f, 0x9a, 0x24, 0x12, 0x06, 0x25, 0x4f,
	0x9a, 0xbc, 0xb2, 0xb9, 0x18, 0xcb, 0x5a, 0x7d, 0x90, 0x1c, 0xad, 0x4e, 0xfa, 0xd0, 0xbd, 0xec,
	0x9e, 0xb3, 0xa1, 0x6e, 0x1c, 0xab, 0x65, 0xd8, 0xef, 0x25, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x1a,
	0x19, 0x36, 0x1e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	Sum(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error)
}

type sumServiceClient struct {
	cc *grpc.ClientConn
}

func NewSumServiceClient(cc *grpc.ClientConn) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcResponse, error) {
	out := new(CalcResponse)
	err := c.cc.Invoke(ctx, "/calc.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	Sum(context.Context, *CalcRequest) (*CalcResponse, error)
}

// UnimplementedSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (*UnimplementedSumServiceServer) Sum(ctx context.Context, req *CalcRequest) (*CalcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calculator_proto_ex/calculator_proto_experimental.proto",
}
